controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lbr_virtual_force_torque_broadcaster:
      type: lbr_broadcasters/LBRVirtualForceTorqueBroadcaster

lbr_virtual_force_torque_broadcaster:
  ros__parameters:
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
    kinematics_plugin: kinematics_interface_kdl/KinematicsInterfaceKDL
    end_effector_name: lbr_link_ee
    sensitivity_offset: [3.0, 3.0, 3.0, 1.5, 1.5, 1.5]
    singular_damping: 0.2
