controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lbr_switch_controller:
      type: lbr_position_controllers/LBRSwitchController

lbr_switch_controller:
  ros__parameters:
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
    kinematics_plugin: kinematics_interface_kdl/KinematicsInterfaceKDL
    end_effector_name: lbr_link_ee
    position_alpha: 0.005

    joint_external_torque_alpha: 0.005
    joint_sensitivty_offset: [5., 5., 5., 5., 1., 1., 1.]
    joint_joint_gains: [10., 10., 10., 10., 10., 10., 10.]

    cartesian_external_torque_alpha: 0.1
    cartesian_sensitivity_offset: [3.0, 3.0, 3.0, 0.5, 0.5, 0.5]
    cartesian_gains: [40., 0., 0., 0., 0., 0.]
    singular_damping: 0.15
    cartesian_joint_gains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
