controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    point_to_point_controller:
      type: lbr_position_controllers/PTPController

point_to_point_controller:
  ros__parameters:
    command_interfaces:
      - "position"
    state_interfaces:
      - "position"
    velocity_scaling: 0.01
    acceleration_scaling: 0.1
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
