controller_manager:
  ros__parameters:
    update_rate: 100

    lbr_virtual_force_torque_broadcaster:
      type: lbr_broadcasters/LBRVirtualForceTorqueBroadcaster

lbr_virtual_force_torque_broadcaster:
  ros__parameters:
    state_interfaces:
      - external_torque
    joints:
      - lbr_joint_0
      - lbr_joint_1
      - lbr_joint_2
      - lbr_joint_3
      - lbr_joint_4
      - lbr_joint_5
      - lbr_joint_6
